### ISSUE TITLE
No pre-trained model

### ISSUE THREAD

**Issue by MKCarter** [czodrowskilab/Machine-learning-meets-pKa#1]
Hi, 

I have setup the conda environment, but when I run:

```
python predict_sdf.py pka_ligands.sdf pka_ligands_pred.sdf
Loading SDF...
2 molecules loaded
Loading model...
Traceback (most recent call last):
  File "predict_sdf.py", line 41, in <module>
    with open('RF_CV_FMorgan3_pKa.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'RF_CV_FMorgan3_pKa.pkl'
```

Would you be able to share the pretrained model? 

I understand if it has confidential data, this might not be possible, but I thought I would ask. :)

**Comment by mrcblt** [comment]
Hi @MKCarter, you can easily train the model yourself. Once you have activated your Conda environment and navigated to the repository folder, you can call:

`python train_model.py`

This will train the model using 12 CPU cores. You can adjust this by modifying [line 17](https://github.com/czodrowskilab/Machine-learning-meets-pKa/blob/master/train_model.py#L17) of the script. The file `RF_CV_FMorgan3_pKa.pkl` will then be available.

Please keep in mind, that you also need OpenEye QUACPAC tool installed to use `predict_sdf.py`. If this might not be available you can comment the [lines 51-52](https://github.com/czodrowskilab/Machine-learning-meets-pKa/blob/master/predict_sdf.py#L51). This could lead to a prediction performance decrease.

If you have any further questions, please feel free to ask.

**Comment by MKCarter** [comment]
Hi @mrcblt 
This worked perfectly, thankyou!
