### ISSUE TITLE
make data available under CCZero?

### ISSUE THREAD

**Issue by egonw** [czodrowskilab/Machine-learning-meets-pKa#4]
MIT is a software license. For data, a data license is better (data copyright and software copyright laws are often different). May I ask you to consider making a citable Zenodo or Figshare archive of the data (`novartis_cleaned_mono_unique_notraindata.sdf` etc) under a CCZero license (which is quite like the MIT license but then for data)?

**Comment by mrcblt** [comment]
Hi Egon, thanks for your request. We have now published the datasets separately via Zenodo, you can view the citation details via https://zenodo.org/record/7884512. We chose the [Attribution 4.0 International (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/) licence for the datasets and added additional citation information to the [README.md](https://github.com/czodrowskilab/Machine-learning-meets-pKa/blob/master/README.md) of the project.
