### ISSUE TITLE
ValueError: Input X contains NaN.

### ISSUE THREAD

**Issue by MachineGUN001** [czodrowskilab/Machine-learning-meets-pKa#5]
hi, 

I tried to run the notebook, modeling.ipynb, and the previous cell units ran smoothly, but when it came to this section

```
est_cls = RandomForestRegressor
rf_params = dict(n_estimators=1000, n_jobs=est_jobs, verbose=verbose, random_state=seed)
name = 'RandomForest (n_estimators=1000)'

train_all_sets(est_cls, rf_params, name)
```
the error info:

> ValueError: Input X contains NaN.
> RandomForestRegressor does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

Here the input is made of null values, but I see that none of the previous values have null values inside them. Why is there a null value here, or am I setting the parameter wrong here?

many thanks for your help

best,

Sh-Y

**Comment by mrcblt** [comment]
Hi Sh-Y,

The reason for the error is that new descriptors have been added to RDKit in the meantime (from 200 to 209 available descriptors). In the first code cell you can see that the `not_used_desc` variable is initialised with descriptor names that in many cases produce `NaN` values. Some of the descriptors added in newer versions of RDKit also produce `NaN` values in some cases. These descriptors also need to be added to this list to fix the error.

I will upload a fixed version of the notebook as soon as possible. Another option is to downgrade RDKit to the 2019.09.3 version that was originally used.

Best regards,
Marcel

**Comment by MachineGUN001** [comment]
hi, Marcel,

thanks for your kind help and explanation.
that works after rdkit was downgraded to 2019.3, however I highly look forward to your update of the notebooks for the new version of RDKit.

many many thanks,

Best,

Sh-Y

**Comment by mrcblt** [comment]
Hi Sh-Y,

I updated the notebook. It works now with the newest RDKit version.

Best,
Marcel

**Comment by MachineGUN001** [comment]
> Hi Sh-Y,
> 
> I updated the notebook. It works now with the newest RDKit version.
> 
> Best, Marcel

Hi, Marcel,

thanks for your update so much! 

Best,
Sh-Y
